name: Creat New Release Tag

on: workflow_dispatch

permissions:
  contents: write
  
jobs:
  create_release_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set Release Version
        id: create_release
        run: |
          mvn versions:set versions:commit -DremoveSnapshot 
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Prepare release: github-api-${{ steps.new_release.outputs.version }}" 
          tagging_message: 'github-api-${{ steps.new_release.outputs.version }}'
      
      - name: Increment Snapshot Version
        id: next_snapshot
        run: |
          mvn versions:set versions:commit -DnextSnapshot 

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Prepare for next development iteration" 
